FROM docker.io/python:3.12.7-alpine3.20

WORKDIR /app

RUN apk --no-cache add tzdata ca-certificates && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && apk del tzdata

COPY requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY keepalive.py keepalive.py

CMD ["python", "keepalive.py"]